Move built files instead of linking
wincinderith/topicons pull request #12
Opened 2016-10-04 18:57 UTC by ffflorian

The link breaks (thus the plugin doesn't work anymore) when the user moves or deletes the repository folder - I don't consider linking very stable in this case.

I suggest to move the `build` folder into the user's local extension folder, so they don't have to keep the repository on their computer.

2016-10-04 22:09 UTC, wincinderith commented
@bddenhartog In PR #9 we introduced this, and I had my doubts about this exact thing occurring. Since it is presenting an issue, we can still keep the update feature, but copy the build directory over each time instead.

2016-10-04 22:18 UTC, zliebersbach requested changes
I don't think the `build` directory should be completely moved to the installation directory. The `clean` target should be left in to deal with removing the build directory from the source tree.

2016-10-04 22:18 UTC, wincinderith commented on Makefile
> +	mv ${PWD}/build $(EXT_DIR)/$(EXT_NAME)
Should be `cp -vr ...`.

2016-10-04 22:18 UTC, wincinderith commented on Makefile
> -clean:
Clean target should be left in.

2016-10-04 22:18 UTC, wincinderith commented on Makefile
> +update: fetch-updates uninstall build
Install target should be a dependency of the update target.

2016-10-04 22:18 UTC, bddenhartog commented on Makefile
> +update: fetch-updates uninstall build
`update` should depend on `fetch-updates`, `uninstall`, and `install`, since `build` doesn't handle moving the `build/` directory.

2016-10-04 22:20 UTC, bddenhartog commented
Sounds fine to me - I suppose keeping the repository on a user's local machine, in the same directory they initially cloned it in and installed from, isn't something every user is going to do.

**Edit**
Oops, look like we were reviewing at the same time :).

2016-10-04 22:24 UTC, bddenhartog commented on Makefile
> +update: fetch-updates uninstall build
Note that since the `build` target is a dependency of `install`, `update` really only needs to depend on `fetch-updates`, `uninstall`, and `install`.

2016-10-04 22:24 UTC, wincinderith commented
@bddenhartog Perhaps remove your review to avoid confusion. :smile:

2016-10-04 22:25 UTC, bddenhartog commented
@wincinderith I thought I had (per the edit to my previous comment on this thread) -- I don't see my review anywhere. Haven't played around with GitHub's shiny new feature, am I missing something obvious?

2016-10-04 22:46 UTC, wincinderith commented
@bddenhartog Nope, seems to be gone now.

2016-10-05 08:13 UTC, ffflorian commented
@wincinderith 
> Since it is presenting an issue, we can still keep the update feature, but copy the build directory over each time instead.

Alright, I agree with this. I will change my PR accordingly.

2016-10-05 10:19 UTC, zliebersbach requested changes
Awesome! Almost good to go...

2016-10-05 10:19 UTC, wincinderith commented on Makefile
> +    rm -vrf build
Indentation issue.

2016-10-05 10:25 UTC, ffflorian commented on Makefile
> +    rm -vrf build
Oops, sorry! Will fix that.

2016-10-05 16:19 UTC, bddenhartog commented on Makefile
>  update: clean fetch-updates build
The `update` target should depend on `clean`, `fetch-updates`, `uninstall`, and `install`.

2016-10-05 16:19 UTC, sudoforge requested changes

2016-10-05 16:19 UTC, bddenhartog commented on Makefile
>  update: clean fetch-updates build
The `update` target should depend on `clean`, `fetch-updates`, `uninstall`, and `install`.

2016-10-06 00:10 UTC, zliebersbach approved these changes

2016-10-06 00:13 UTC, wincinderith commented on Makefile
>  update: clean fetch-updates build
@ffflorian I'll handle this with a push directly to `master`. Thanks for your contribution!

2016-10-06 00:13 UTC, merged